#!/bin/sh

if [ -z "$1" ]; then
  echo "need url."
else
  curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer ${ACCESS_TOKEN}" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  $1
fi
